import type { ElkLayeredOptionName } from "./elk-options.generated";

/** Every ELK 0.11.1 enum constant, source-locked to its Java declaration. */
export const elkLayeredEnumValues = {
  "wrapping.strategy": ["OFF", "SINGLE_EDGE", "MULTI_EDGE"],
  "wrapping.cutting.strategy": ["ARD", "MSD", "MANUAL"],
  "wrapping.validify.strategy": ["NO", "GREEDY", "LOOK_BACK"],
  "layerUnzipping.strategy": ["NONE", "ALTERNATING"],
  "nodePlacement.networkSimplex.nodeFlexibility": [
    "NONE",
    "PORT_POSITION",
    "NODE_SIZE_WHERE_SPACE_PERMITS",
    "NODE_SIZE",
  ],
  "nodePlacement.networkSimplex.nodeFlexibility.default": [
    "NONE",
    "PORT_POSITION",
    "NODE_SIZE_WHERE_SPACE_PERMITS",
    "NODE_SIZE",
  ],
  "edgeRouting.splines.mode": ["CONSERVATIVE", "CONSERVATIVE_SOFT", "SLOPPY"],
  "topdown.nodeType": ["PARALLEL_NODE", "HIERARCHICAL_NODE", "ROOT_NODE"],
  edgeRouting: ["UNDEFINED", "POLYLINE", "ORTHOGONAL", "SPLINES"],
  portConstraints: ["UNDEFINED", "FREE", "FIXED_SIDE", "FIXED_ORDER", "FIXED_RATIO", "FIXED_POS"],
  "port.side": ["UNDEFINED", "NORTH", "EAST", "SOUTH", "WEST"],
  alignment: ["AUTOMATIC", "LEFT", "RIGHT", "TOP", "BOTTOM", "CENTER"],
  hierarchyHandling: ["INHERIT", "INCLUDE_CHILDREN", "SEPARATE_CHILDREN"],
  "nodeSize.constraints": ["PORTS", "PORT_LABELS", "NODE_LABELS", "MINIMUM_SIZE"],
  "nodeSize.options": [
    "DEFAULT_MINIMUM_SIZE",
    "MINIMUM_SIZE_ACCOUNTS_FOR_PADDING",
    "COMPUTE_PADDING",
    "OUTSIDE_NODE_LABELS_OVERHANG",
    "PORTS_OVERHANG",
    "UNIFORM_PORT_SPACING",
    "SPACE_EFFICIENT_PORT_LABELS",
    "FORCE_TABULAR_NODE_LABELS",
    "ASYMMETRICAL",
  ],
  direction: ["UNDEFINED", "RIGHT", "LEFT", "DOWN", "UP"],
  "nodeLabels.placement": [
    "H_LEFT",
    "H_CENTER",
    "H_RIGHT",
    "V_TOP",
    "V_CENTER",
    "V_BOTTOM",
    "INSIDE",
    "OUTSIDE",
    "H_PRIORITY",
  ],
  "portLabels.placement": [
    "OUTSIDE",
    "INSIDE",
    "NEXT_TO_PORT_IF_POSSIBLE",
    "ALWAYS_SAME_SIDE",
    "ALWAYS_OTHER_SAME_SIDE",
    "SPACE_EFFICIENT",
  ],
  "portAlignment.default": ["DISTRIBUTED", "JUSTIFIED", "BEGIN", "CENTER", "END"],
  "portAlignment.north": ["DISTRIBUTED", "JUSTIFIED", "BEGIN", "CENTER", "END"],
  "portAlignment.south": ["DISTRIBUTED", "JUSTIFIED", "BEGIN", "CENTER", "END"],
  "portAlignment.west": ["DISTRIBUTED", "JUSTIFIED", "BEGIN", "CENTER", "END"],
  "portAlignment.east": ["DISTRIBUTED", "JUSTIFIED", "BEGIN", "CENTER", "END"],
  "layering.strategy": [
    "NETWORK_SIMPLEX",
    "LONGEST_PATH",
    "LONGEST_PATH_SOURCE",
    "COFFMAN_GRAHAM",
    "INTERACTIVE",
    "STRETCH_WIDTH",
    "MIN_WIDTH",
    "BF_MODEL_ORDER",
    "DF_MODEL_ORDER",
  ],
  "layering.nodePromotion.strategy": [
    "NONE",
    "NIKOLOV",
    "NIKOLOV_PIXEL",
    "NIKOLOV_IMPROVED",
    "NIKOLOV_IMPROVED_PIXEL",
    "DUMMYNODE_PERCENTAGE",
    "NODECOUNT_PERCENTAGE",
    "NO_BOUNDARY",
    "MODEL_ORDER_LEFT_TO_RIGHT",
    "MODEL_ORDER_RIGHT_TO_LEFT",
  ],
  "layering.layerConstraint": ["NONE", "FIRST", "FIRST_SEPARATE", "LAST", "LAST_SEPARATE"],
  "cycleBreaking.strategy": [
    "GREEDY",
    "DEPTH_FIRST",
    "INTERACTIVE",
    "MODEL_ORDER",
    "GREEDY_MODEL_ORDER",
    "SCC_CONNECTIVITY",
    "SCC_NODE_TYPE",
    "DFS_NODE_ORDER",
    "BFS_NODE_ORDER",
  ],
  "crossingMinimization.strategy": ["LAYER_SWEEP", "MEDIAN_LAYER_SWEEP", "INTERACTIVE", "NONE"],
  "crossingMinimization.greedySwitch.type": ["ONE_SIDED", "TWO_SIDED", "OFF"],
  "crossingMinimization.greedySwitchHierarchical.type": ["ONE_SIDED", "TWO_SIDED", "OFF"],
  interactiveReferencePoint: ["CENTER", "TOP_LEFT"],
  "nodePlacement.strategy": [
    "SIMPLE",
    "INTERACTIVE",
    "LINEAR_SEGMENTS",
    "BRANDES_KOEPF",
    "NETWORK_SIMPLEX",
  ],
  "nodePlacement.bk.fixedAlignment": [
    "NONE",
    "LEFTUP",
    "RIGHTUP",
    "LEFTDOWN",
    "RIGHTDOWN",
    "BALANCED",
  ],
  "edgeRouting.selfLoopDistribution": ["EQUALLY", "NORTH", "NORTH_SOUTH"],
  "edgeRouting.selfLoopOrdering": ["STACKED", "REVERSE_STACKED", "SEQUENCED"],
  contentAlignment: ["V_TOP", "V_CENTER", "V_BOTTOM", "H_LEFT", "H_CENTER", "H_RIGHT"],
  "nodePlacement.bk.edgeStraightening": ["NONE", "IMPROVE_STRAIGHTNESS"],
  "compaction.postCompaction.strategy": [
    "NONE",
    "LEFT",
    "RIGHT",
    "LEFT_RIGHT_CONSTRAINT_LOCKING",
    "LEFT_RIGHT_CONNECTION_LOCKING",
    "EDGE_LENGTH",
  ],
  "compaction.postCompaction.constraints": ["QUADRATIC", "SCANLINE"],
  "edgeLabels.placement": ["CENTER", "HEAD", "TAIL"],
  "edgeLabels.sideSelection": [
    "ALWAYS_UP",
    "ALWAYS_DOWN",
    "DIRECTION_UP",
    "DIRECTION_DOWN",
    "SMART_UP",
    "SMART_DOWN",
  ],
  "edgeLabels.centerLabelPlacementStrategy": [
    "MEDIAN_LAYER",
    "TAIL_LAYER",
    "HEAD_LAYER",
    "SPACE_EFFICIENT_LAYER",
    "WIDEST_LAYER",
    "CENTER_LAYER",
  ],
  directionCongruency: ["READING_DIRECTION", "ROTATION"],
  portSortingStrategy: ["INPUT_ORDER", "PORT_DEGREE"],
  "considerModelOrder.strategy": ["NONE", "NODES_AND_EDGES", "PREFER_EDGES", "PREFER_NODES"],
  "considerModelOrder.longEdgeStrategy": ["DUMMY_NODE_OVER", "DUMMY_NODE_UNDER", "EQUAL"],
  "considerModelOrder.components": [
    "NONE",
    "INSIDE_PORT_SIDE_GROUPS",
    "GROUP_MODEL_ORDER",
    "MODEL_ORDER",
  ],
  "considerModelOrder.groupModelOrder.cbGroupOrderStrategy": [
    "ONLY_WITHIN_GROUP",
    "MODEL_ORDER",
    "ENFORCED",
  ],
  "considerModelOrder.groupModelOrder.cmGroupOrderStrategy": [
    "ONLY_WITHIN_GROUP",
    "MODEL_ORDER",
    "ENFORCED",
  ],
} as const satisfies Partial<Record<ElkLayeredOptionName, readonly string[]>>;

export type ElkLayeredEnumOptionName = keyof typeof elkLayeredEnumValues;
