import ELK from "elkjs/lib/elk.bundled.js";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const OUTPUT_URL = new URL("../src/layered/elk-options.generated.ts", import.meta.url);
const ELK_PREFIX = "org.eclipse.elk.";

const SIMPLE_NAME_OVERRIDES = new Map([
  ["spacing.nodeNode", "spacing.node"],
  ["layered.spacing.nodeNodeBetweenLayers", "spacing.layer"],
]);

function getSimpleName(id: string): string {
  const suffix = id.startsWith(ELK_PREFIX) ? id.slice(ELK_PREFIX.length) : id;
  return SIMPLE_NAME_OVERRIDES.get(suffix) ?? suffix.replace(/^layered\./, "");
}

function getValueType(type: string | undefined): string {
  switch (type) {
    case "BOOLEAN":
      return "boolean";
    case "DOUBLE":
    case "INT":
      return "number";
    case "ENUM":
    case "ENUMSET":
    case "STRING":
      return "string";
    case "OBJECT":
      return "unknown";
    default:
      throw new Error(`Unsupported ELK option type: ${type ?? "undefined"}`);
  }
}

const elk = new ELK();
const [algorithms, options] = await Promise.all([
  elk.knownLayoutAlgorithms(),
  elk.knownLayoutOptions(),
]);
const layered = algorithms.find((algorithm) => algorithm.id === "org.eclipse.elk.layered");
if (!layered?.knownOptions) throw new Error("ELK layered option inventory is unavailable");

const metadataById = new Map(options.map((option) => [option.id, option]));
const definitions = layered.knownOptions.map((id) => {
  const metadata = metadataById.get(id);
  if (!metadata) throw new Error(`Missing metadata for ${id}`);
  return {
    name: getSimpleName(id),
    id,
    type: metadata.type,
    targets: metadata.targets ?? [],
    valueType: getValueType(metadata.type),
  };
});

const names = definitions.map((definition) => definition.name);
const duplicateNames = names.filter((name, index) => names.indexOf(name) !== index);
if (duplicateNames.length > 0) {
  throw new Error(
    `Simplified ELK option names collide: ${[...new Set(duplicateNames)].join(", ")}`,
  );
}

const lines = [
  "// Generated by scripts/generate-elk-layered-options.ts from elkjs 0.11.1.",
  "// Do not edit manually.",
  "",
  "export interface ElkLayeredOptionValueByName {",
  ...definitions.map(({ name, valueType }) => `  ${JSON.stringify(name)}?: ${valueType};`),
  "}",
  "",
  "export const elkLayeredOptionDefinitions = [",
  ...definitions.map(
    ({ name, id, type, targets }) =>
      `  { name: ${JSON.stringify(name)}, elkId: ${JSON.stringify(id)}, type: ${JSON.stringify(type)}, targets: ${JSON.stringify(targets)} },`,
  ),
  "] as const;",
  "",
  "export type ElkLayeredOptionName = keyof ElkLayeredOptionValueByName;",
  'export type ElkLayeredOptionId = (typeof elkLayeredOptionDefinitions)[number]["elkId"];',
];

const output = `${lines.join("\n")}\n`;
if (process.argv.includes("--check")) {
  const current = await readFile(OUTPUT_URL, "utf8");
  if (current !== output) {
    throw new Error(`${fileURLToPath(OUTPUT_URL)} is stale; run pnpm generate:elk-layered-options`);
  }
  console.log(`Verified ${definitions.length} ELK layered option mappings`);
} else {
  await writeFile(OUTPUT_URL, output);
  console.log(
    `Generated ${definitions.length} ELK layered options in ${fileURLToPath(OUTPUT_URL)}`,
  );
}
